### ISSUE TITLE
[Request] Lower Forge requirements

### ISSUE THREAD

**Issue by accessdenied0** [HenryLoenwind/EnderIOAddons#1]
Hey @HenryLoenwind,

Your mod looks very interesting and I would like to very much to use it, but sadly your mod uses the newest release from Forge witch is 10.13.4.1492 as minimum instead of the recommend (bug-free) version 10.13.4.1448.

My request is now If you would be so kindly to reduce the Forge requirements to 10.13.4.1448, so I'm able to use your mod with the recommend versions of Forge.

I'm aware you don't have to, but I would be very thank full,

access_denied

**Comment by HenryLoenwind** [comment]
The lowest I could lower it to is 10.13.4.1490, that is the one EnderCore requires.

**Comment by accessdenied0** [comment]
Hey @HenryLoenwind,

?!?!? I use the latest EnderCore (EnderCore-1.7.10-0.1.0.24_beta.jar) and it does clearly work with Forge 10.13.4.1448... besides it would not make any sense because all versions over 1448 are experimental (with bugs and stuff (or maybe I'm wrong?))... are you really sure about that?

If yes, I'm going to ask the Ender IO -staff, I believe there is a solution.

access_denied

**Comment by HenryLoenwind** [comment]
EnderCore is a bit sneaky there. It is compiled against 1490 but doesn't export that as a runtime requirement.

**Comment by HenryLoenwind** [comment]
Could you try http://loenwind.info/eioa/EnderIOAddons-1.7.10-0.1.0.0_master_5156065_beta.jar ? It has its Forge dependency removed.

**Comment by accessdenied0** [comment]
@HenryLoenwind,

Thank you, but this version destroys the world. It scrambles the whole Block-ID's and makes the world unplayable... It is very strange :/

I asked the Ender-core team, maybe they know more. It nothing helps and if it is valid I have to update.

access_denied

**Comment by accessdenied0** [comment]
@HenryLoenwind,

I did remove some mods and retried your mod version you gave me. I have to apologize for my suggestion that this mod corrupts worlds... It seems to work just fine. I can place, access and look up the recipe. The only issue I have to point out is that I somehow just can get Gravel from Cobblestone if I use the SAG mill in your machine. It is strange and maybe is a issue with Ex-Nihilo (I disabled the recipe-override "Cobble-To-Gravel")...

access_denied

**Comment by HenryLoenwind** [comment]
Thx for the feedback. I suspected as much.

The mixed up outputs are a bug in that version. The new one up on curse has it fixed and lower Forge dependencies, too.

**Comment by accessdenied0** [comment]
@HenryLoenwind,

Thank you a lot,
I now use the newest version. But I have noticed that the "SAG-Mill" step still put first Gravel (until it is a whole stack) and than Sand out. Is this supposed to happen or I just using the wrong version? (It is the version _"EnderIOAddons-1.7.10-0.1.0.003_beta"_)

access_denied

**Comment by HenryLoenwind** [comment]
Oh, about the order. Yes, it is working from the last slot to the first. This has been done on purpose so it will be faster refilling whatever you took out---it can potentially do all 4 steps in one tick instead of needing one tick per step.

**Comment by accessdenied0** [comment]
@HenryLoenwind,

That is really clever, so it saves a lot of ticks and fps. Just a bit fast, but really neat. I didn't have any further issues so far, but I let you know If I find one.

Thanks a lot for your time and help

access_denied
