### ISSUE TITLE
Capacitor Crops issues?

### ISSUE THREAD

**Issue by zoeliterally** [HenryLoenwind/EnderIOAddons#10]
Setup: ![Setup](http://i.imgur.com/Os2HBxh.png)
Grow phase, everything ok: ![Growth phase](http://i.imgur.com/aKEOC9l.png)
Mature, _This plant can not grow here_ and produces nothing: ![Mature](http://i.imgur.com/0YDHNqL.png)

PEBCAK?

**Comment by HenryLoenwind** [comment]
The "cannot grow here" is normal for mature plants, it is to stop them from getting growth ticks (which AgriCraft would happily send) which consume energy.

Is it just seeds with "gain" 10 that do not produce stuff?

(PS: You did right-click them to harvest, didn't you?)

**Comment by zoeliterally** [comment]
Unanalyzed and 1-1-1 seeds also. Server/client snyc problem?

**Comment by HenryLoenwind** [comment]
Plant logic should run completely on the server. And it's not actually much I do, most of it is AgriCraft.

Could you run this version, harvest and look in the server logfile for a line `[enderioaddons]: Returning harvest:`? Thanks.

http://loenwind.info/eioa/EnderIOAddons-1.7.10-2.3.0.420_beta-0.9.7.032_beta.jar

**Comment by zoeliterally** [comment]
Now it works, log:
[enderioaddons.log](https://gist.github.com/Calenria/22bb2555c792a71f846e#file-enderioaddons-log-L247)

**Comment by HenryLoenwind** [comment]
I swear, I didn't change anything near the plant but for that debug log...

**Comment by zoeliterally** [comment]
maybe it's a very communicative plant :)

i close it for now
