### ISSUE TITLE
Loot Recycler did this to me...

### ISSUE THREAD

**Issue by therealericbj** [HenryLoenwind/EnderIOAddons#11]
I have just discovered your mod and have been eagerly anticipating using it, but was waiting for the Yeta Wrench fix to be released.  ...it was.

Installed latest versions of Endercore, EnderIO, EnderIOAddons and Waterhooks.

Went into an existing SSP world that I had been testing things in.

Grabbed a Recycler and tried to place it in the world to look at it/into it.  I wanted to know what happened to the removed enchantments.

Then it did this to me...
http://openeye.openmods.info/crashes/5f81d63ac2fb0506f29b3687a0b31181

I tried to go back into the same world and was given this...
http://openeye.openmods.info/crashes/180255756e1a1c17889ba353242a7489

I tried creating a new SSP world and then tried again to place a Recycler in the world.  Was given the first error again.

This makes me sad.  I want to play with the cool toys you have made for one of my favorite mods.

What do I do to make this work?  ...tell me, tell me, tell me...  :P

**Comment by HenryLoenwind** [comment]
New build has been uploaded to curse.

**Comment by therealericbj** [comment]
Problem solved.

Even lets me back into my original SSP test world.

Thank you sir.

**Comment by HenryLoenwind** [comment]
NP. And sorry for being so short on the answer. I was on my way to bed when I noticed the issue and fixed it already half asleep. ;)
