### ISSUE TITLE
[Feature Request] Capacitor Seeds

### ISSUE THREAD

**Issue by MaelstromPhx** [HenryLoenwind/EnderIOAddons#12]
Currently working on a sky block modpack that has Ender IO Addons in it. Loving it so far but I'm having some issues concerning the capacitor seeds, since there is no bedrock available. Thought of some stuff to maybe fix the issue for maps without access to bedrock.
- Option to play without the seed. Just take it out completely and play with the 'cheat' mode recipes but remove all the other recipes so that they don't clutter NEI and confuse the players.
- Change the soil. Would love this feature because I think the idea is actually pretty nifty. Just a spot in the config to put down a block ID or name of some kind to replace bedrock as the needed block.
- Option to remove any recipes concerning the seed/products. Same as option 1 but the change to 'cheat' mode recipes is manual.

Would really help me out if this was possible :smile:

Side Note: The cobble works with built in machines is amazing and I love you for it!

**Comment by HenryLoenwind** [comment]
The needed block can be changed using MineTweaker3, see AgriCraft's documentation on it. That's why I didn't add an option to Ender IO Addons for it.

https://github.com/InfinityRaider/AgriCraft/wiki/%5B1.3.%2A%5D-MineTweaker3#baseblock

**Comment by MaelstromPhx** [comment]
I feel like an idiot. I've read that document :stuck_out_tongue:
Thanks for pointing it out.

In that case would it be possible to make an option to remove the standard ender io recipes for the higher tier capacitors? I can do it via minetweaker but disabling the recipes for the double and octadic ones would remove the Ender IO Addons recipes as well and since I'd have to remake them its a bit redundant.

**Comment by MaelstromPhx** [comment]
Also getting an error when trying to clear the base Block.

import mods.agricraft.growing.BaseBlock;
BaseBlock.clear(enderioaddons:itemMachineParts:22);

gives me

ERROR: Seeds has to be non-null and of type ItemSeeds.

**Comment by HenryLoenwind** [comment]
Ok, it seems AgriCraft is a bit tight on the type checking here. @InfinityRaider: Can you extend your code to work with all seeds that have an IGrowthRequirement or do I need to add support for configs/MineTweaker to Ender IO Addons for this?

**Comment by InfinityRaider** [comment]
Someone else has aked this as well, this is an archaic remnant from pre-1.3, where I grabbed everything I needed form the vanilla ItemSeeds class, but because more mods implement there own seed class instead of using the Minecraft one I changed to another system.
I must have overlooked that check when I chagned my system, but in the next release it should also be gone: https://github.com/InfinityRaider/AgriCraft/commit/e560276721ec4c3a6ac2788ee8475e8c1b7e1bda

**Comment by Keridos** [comment]
@InfinityRaider @HenryLoenwind 
Still does not work with Agricraft 1.4.6 for me: `info.loenwind.enderioaddons.machine.part.ItemMachinePart cannot be cast to net.minecraft.item.ItemSeeds`

**Comment by InfinityRaider** [comment]
Ye my bad, I missed some more of those checks..., should be fixed in next version though, my apologies.

**Comment by Keridos** [comment]
@InfinityRaider Still does not work on 1.5.0 for me.

**Comment by HenryLoenwind** [comment]
A config for this will be in the next version

**Comment by Keridos** [comment]
Ok, thanks a lot :)
