### ISSUE TITLE
[Bug] Cobbleworks Not Consuming Energy

### ISSUE THREAD

**Issue by MaelstromPhx** [HenryLoenwind/EnderIOAddons#13]
Basically the title. I have the Cobbleworks hooked up to a basic capacitor bank and it drain's the initial 100,000 RF to fill the internal buffer but no more than that. Instantly produces stacks of cobblestone and instantly performs all processing actions as well with no power costs. Settings are default, with 10 percent power reduction on each processing action and 100 RF per cobblestone.

Ender IO version: 2.3.0.421_beta
Ender IO Addons version: 2.3.0.421_beta-0.9.8.034_beta

**Comment by HenryLoenwind** [comment]
Oops, the whole mod defaulted to that mode being on instead being off.

Thx for reporting this.
