### ISSUE TITLE
Capacitor Seeds image not right...

### ISSUE THREAD

**Issue by therealericbj** [HenryLoenwind/EnderIOAddons#14]
I don't think this is what you were going for...

![seed-storage](https://cloud.githubusercontent.com/assets/8407817/11459175/1792e714-9696-11e5-9e96-964a093b542a.png)

Could this also be related to...

https://github.com/SleepyTrousers/EnderIO/issues/3041

Forge 1558
EnderIO-1.7.10-2.3.0.421_beta.jar
EnderCore-1.7.10-0.2.0.31_beta.jar
EnderIOAddons-1.7.10-2.3.0.421_beta-0.9.8.034_beta.jar
AgriCraft-1.7.10-1.4.5.jar

**Comment by HenryLoenwind** [comment]
That item is rendered by the vanilla item renderer, so nothing I can do about that.

Update: Found the error and reported it.

**Comment by HenryLoenwind** [comment]
See the linked issue at AgriCraft. Bug on their side will be fixed.
