### ISSUE TITLE
java.lang.ClassNotFoundException: com.InfinityRaider.AgriCraft.api.API

### ISSUE THREAD

**Issue by Tsyklop** [HenryLoenwind/EnderIOAddons#19]
Error in the log: http://pastebin.com/zvj2Aes0

AgriCraft not installed. EnderIOAddons-1.7.10-2.3.0.421_beta-0.9.9.036_beta

**Comment by HenryLoenwind** [comment]
This cuts off just before the interesting part. I know the stack trace to the call I make to get the API, I need the one for the error that caused it to fail.
