### ISSUE TITLE
Suggestion: Release addon after primary mod

### ISSUE THREAD

**Issue by walkerjonny** [HenryLoenwind/EnderIOAddons#28]
It causes unnecessary issues if the addon gets released before the main mod.
In this case EnderIO-1.7.10-2.3.0.423 beta is still not officially published on curse/curseforge.
I for myself know how to get to the Jenkins server of EnderIO but others do not.
Please keep that in mind before releasing a new version of the addon that depends on a unreleased version of EnderIO.

**Comment by Tsyklop** [comment]
http://ci.tterrag.com/job/EnderIO/423/
