### ISSUE TITLE
Loot recycler not exporting recycled material

### ISSUE THREAD

**Issue by Staegrin** [HenryLoenwind/EnderIOAddons#29]
I've set up the Loot recycler to take loot from the alchemical chest and to export to the vanilla chest next to it.
Ender IO version 1.7.10-2.3.0.422
Ender IO Addons version 2.3.0.422_beta_0.10.3.046
![2016-01-10_15 45 15](https://cloud.githubusercontent.com/assets/8494635/12222103/50bdbe3c-b7b2-11e5-8fe1-9dc497112e6b.png)
![2016-01-10_15 45 27](https://cloud.githubusercontent.com/assets/8494635/12222104/52596df4-b7b2-11e5-96dd-6dfd75eebd0c.png)

It just keeps building up in the internal buffer. Can't pull it out with other mods as well.

**Comment by HenryLoenwind** [comment]
You need to press the "get" button. The output slot (lower left) can be pulled out; the internal buffer cannot be.
