### ISSUE TITLE
[Suggestion] Add recipe to upgrade existing Farming Stations to AgriCraft-compatible one

### ISSUE THREAD

**Issue by hron84** [HenryLoenwind/EnderIOAddons#32]
It would be good if exiring Farming Stations can be upgraded somehow to support Agricraft seeds. It's important because there would be a scenario when someone makes a farm system with normal EIO Farming Stations (as EIO ones can harvest crops too, even if they're not too smart in this term), and when there's enough resource wants to replace them with EIOA ones but without wasting original ones.

**Comment by HenryLoenwind** [comment]
This will be in the next version.

**Comment by hron84** [comment]
@HenryLoenwind cool, thanks!
