### ISSUE TITLE
Self resetting lever time incorrect.

### ISSUE THREAD

**Issue by zombiethoughts** [HenryLoenwind/EnderIOAddons#34]
The self resetting levers are described as being reset after 10 seconds, 30 seconds, and 1 minute.
It should read ticks, as actual times are .5 seconds(ten ticks), 1.5 seconds(30 ticks), and 3 seconds(60 ticks).

I like the times as they are, and would love to see buttons also. Buttons for iron doors with these short times are perfect. No more getting blocked at an iron door due to lag on a server.

Love these additions to Ender IO. Keep up the great work.

**Comment by HenryLoenwind** [comment]
This actually has been fixed already, I just have been waiting with a release for Ender IO to have its latest release public. Didn't expect that to take so long.

I'll think about the buttons. Sounds useful.
