### ISSUE TITLE
How do I make disable organic capacitor?

### ISSUE THREAD

**Issue by karakufire** [HenryLoenwind/EnderIOAddons#35]
I don't like capacitor crops, so I try to make disable this.
but no entries enable/unable new seed for agricraft I found in config.

**Comment by HenryLoenwind** [comment]
They are disabled together with the Agricraft Farming station. There's a config setting to add plant-less crafting recipes, but none to disable the plant independently of the farm.

**Comment by HenryLoenwind** [comment]
a config for this will be in the next version
