### ISSUE TITLE
Capacitor Seeds 

### ISSUE THREAD

**Issue by bthrom** [HenryLoenwind/EnderIOAddons#36]
I have got them to grow and leveled up to 10 10 10 I wanted to know how get the capacitors to grow as a crop product? I have got end the gel and the housing, and a few organic capacitors?

**Comment by HenryLoenwind** [comment]
yes, those are the main fruits of the plant. There are recipes for making capacitors out of these components. A ready-to-use capacitor is a (very) rare drop.

**Comment by bthrom** [comment]
Ok just wanted to make sure it wasn't how I had things set up and needed an upgraded  bank underneath to get better yields or something like that
