### ISSUE TITLE
Capacitor Plants Not Getting Harvested With Agricraft Farming Station

### ISSUE THREAD

**Issue by bthrom** [HenryLoenwind/EnderIOAddons#37]
I have set up an Agricraft Farming Station to control the plating and harvesting of my Capacitor Seeds/Plants, the Harvest Unanalyzed Plants module, Seed Multiplying module, and the Seed Analyzer module all work(manually bread to 10 10 10) I have gotten my farm full of Mature plants, however, it is not harvesting them, and my hoe is taking durability loss like it is. 

![2016-05-16_15 29 17](https://cloud.githubusercontent.com/assets/19314475/15303039/7e9b18cc-1b7b-11e6-92e3-8a8ad3a8105c.png)
![2016-05-16_15 30 42](https://cloud.githubusercontent.com/assets/19314475/15303003/54641b30-1b7b-11e6-9279-63c5bbf7499d.png)
![2016-05-16_15 30 38](https://cloud.githubusercontent.com/assets/19314475/15303004/54658ae2-1b7b-11e6-9d17-1c2137f90a5a.png)
![2016-05-16_15 30 40](https://cloud.githubusercontent.com/assets/19314475/15303005/5466ee8c-1b7b-11e6-9980-2802727f60c6.png)
![2016-05-16_15 30 41](https://cloud.githubusercontent.com/assets/19314475/15303006/54693228-1b7b-11e6-9f80-1bc5c2b209f3.png)

**Comment by HenryLoenwind** [comment]
Check your config file, is "seedsAutomaticHarvestingEnabled" set to false? (that's the default)

**Comment by bthrom** [comment]
Ok it is a balance issue, I wasnt sure if it was supposed to and wasnt but it is not supposed to

**Comment by HenryLoenwind** [comment]
Yes it is. However, now that I think about it, it seems I forgot to mention that restriction somewhere in the seed description. Sorry.
