### ISSUE TITLE
Graphical Power Monitor causes server crash when placed

### ISSUE THREAD

**Issue by tecer0** [HenryLoenwind/EnderIOAddons#4]
EnderIO-1.7.10-2.3.0.417_beta
EnderCore-1.7.10-0.2.0.30_beta
EnderIOAddons-1.7.10-2.3.0.417_beta-0.8.0.015_beta
forge-1.7.10-10.13.4.1448-1.7.10-universal

Full crash report -> http://pastebin.com/DBhzGM3M

**Comment by Rukachan** [comment]
Since 0.8.1 is out for quite some time and I can't replicate this bug, I think the issue can be closed?

**Comment by HenryLoenwind** [comment]
oops, I didn't remember I left this open. ;)
