### ISSUE TITLE
Capacitor seed questions

### ISSUE THREAD

**Issue by Nibbler230** [HenryLoenwind/EnderIOAddons#44]
First off, what an amazing mod!

Second I was hoping to get some information about the Capacitor seeds.
I have made them work just fine, got them to 10,10,10 and they produce.
But after harvesting over 100 times I think I got 2 basic capacitors, and tons of the organic shells, gel, and cores.

Can I ask what are the chances of getting more basic capacitors or even the double-Layer and octadic capacitors? Is there anyway to increase these chances? Have seeds sit on a vibrant capacitor bank compared to a basic capacitor bank?

And what can we do with the organic stuff besides the farming station upgrades? I'm playing Project Ozone 2 reloaded on Kappa mode so recipies may just be disabled but otherwise I see no use for them.

Thank you so much for your help! I wish there was a ftb wiki page on this mod (future project?)

**Comment by HenryLoenwind** [comment]
The chances are in the 1:10000 range, fully formed capacitors are a very rare drop. By default there are recipes to make capacitors from the low level drops and some redstone. As far as I heard, that pack has disabled them, making the seeds a bit useless, apart from making the AFS modules...

**Comment by Nibbler230** [comment]
Thank you for the fast reply! Really good to know so I didn't put any more time into these, o well, i got the AFS now :D
