### ISSUE TITLE
Magnetic flags malfunctioning when looked at

### ISSUE THREAD

**Issue by piepie62** [HenryLoenwind/EnderIOAddons#47]
Ender IO Addons Version: 0.10.11
Ender IO Version: 1.7.10-2.3.0.429_beta
Endercore Version: 1.7.10-0.2.0.36_beta
Forge Version: 10.13.4.1614

I am currently trying to use the Magnetized Flags on a self-made server using the Unabridged ATLauncher modpack, modpack version 1.7.10.Release.14. For some reason, whenever I look at the magnetic flags, they stop working correctly. The flags "unmagnetize" themselves when I look at them, and only work correctly if I go into a different dimension and come back. Then they are working perfectly. I am not certain what could be causing it, but my first thought is some conflict between WAILA and EnderIOAddons. I don't see how that would do anything like this, however.

Before looking:
![2017-03-14_19 31 18](https://cloud.githubusercontent.com/assets/8108982/23926839/e8698324-08ec-11e7-83d7-627a9e7a7097.png)
After looking:
![2017-03-14_19 31 22](https://cloud.githubusercontent.com/assets/8108982/23926853/f8cf1558-08ec-11e7-92a2-400f38e0785c.png)
Looking away after looking:
![2017-03-14_19 31 26](https://cloud.githubusercontent.com/assets/8108982/23926862/099663b4-08ed-11e7-9eb2-68defb70e85d.png)
After dimension change:
![2017-03-14_19 31 41](https://cloud.githubusercontent.com/assets/8108982/23926882/1d42b9e4-08ed-11e7-9618-1b9154eedd40.png)

**Comment by piepie62** [comment]
Looking at the client log, it seems to have something to do with packet handling and, as I suspected, WAILA and EnderIOAddons conflicting somehow.

[Client Log](https://paste.ee/p/CZoBB)

**Comment by HenryLoenwind** [comment]
Thx for the log, I see what's happening. WAILA runs the same code as creative mode "pick block" (middle mouse click), which goes into the same code as breaking the block. Which is not really good as flags can demagnetize when broken. And then the code runs client-side, which gives you the desync.

Easy to fix. I just need my eioa dev env, so it has to wait until the weekend.

**Comment by piepie62** [comment]
Nice prompt fix; sorry it took me so long to test. Closing.
