### ISSUE TITLE
Agricraft Farming Station crashes when trying to insert any hoe

### ISSUE THREAD

**Issue by atoms2ashes** [HenryLoenwind/EnderIOAddons#52]
I tested this out using nothing but Forge and other libraries related to EIO and EIO Addons.

Crash log (and thus included mods) can be found here:  https://pastebin.com/1bdsmTTi

**Comment by HenryLoenwind** [comment]
Agricraft returns an invalid item when being asked for all available rakes. Try updating Agricraft.

**Comment by atoms2ashes** [comment]
Initially updating Agricraft didn't do the trick but since you mentioned invalid items, I decided to check the config I was using if any items were disabled.

It turns out in the config file I was using, the weeds and default Agricraft rakes were disabled altogether and reenabling them made the machine return no further errors.

Thank you so much for the help.
