### ISSUE TITLE
Till Aggressively in Agricraft Farming Station (SMP)

### ISSUE THREAD

**Issue by jburrows82** [HenryLoenwind/EnderIOAddons#8]
Using 0.9.5 (thanks for the quick fix btw!), when clicking the "Till Aggressively" option in the Argricraft Farming Station GUI, the client gets disconnected from the server.

Nothing in client log. Only receive the connection lost screen "A fatal error has occured, this connection is terminated"

http://pastebin.com/yDmgAkXi <-- server side log (trimmed, full log attached)

[fml-server-latest.txt](https://github.com/HenryLoenwind/EnderIOAddons/files/39784/fml-server-latest.txt)

**Comment by HenryLoenwind** [comment]
Thx, I hope that's all. Over 900 downloads on the 0.9.x version, and you're the first to report those errors.

Before I pump that to curse again, could you check it out?

http://loenwind.info/eioa/EnderIOAddons-1.7.10-2.3.0.420_beta-0.9.5.029_beta.jar

**Comment by jburrows82** [comment]
That fixed it! Thank you!

Another semi-related issue:

In the config for the aggressively tilled default on/of, you're missing 'a' in aggressively

"agricraft farming station" {
    # The initial value of 'till gressively' for newly placed farms

**Comment by HenryLoenwind** [comment]
Thx very much, new version is uploading now.
